#! /bin/bash

docker run -d \
    --privileged \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /dev/bus/usb:/dev/bus/usb \
    -v $HOME/TomTom\ Sports:/root/TomTom\ Sports \
    -v $HOME/.local/share/TomTom/:/root/.local/share/TomTom/ \
    -e DISPLAY=unix$DISPLAY \
    --name tomtomsc \
    --rm \
    tomtomsc:latest

